from __future__ import annotations

CONFIG_FILE_COMMENTS = [
    "Package-wide Akkadian Prosody Toolkit configuration.",
    "This file uses the repository's restricted YAML subset: nested mappings, scalars, and JSON-style lists.",
    "Common keys apply across file-producing CLIs.",
    "fullprosmaker reads common plus the syllabifier, prosmaker, metricalc, and printer sections.",
]

CONFIG_SECTION_HELP = {
    "common": "Shared options used across file-producing CLIs.",
    "atfparser": "Options specific to the atfparser CLI.",
    "syllabifier": "Options used by the syllabifier CLI and by fullprosmaker during the syllabify stage.",
    "prosmaker": "Options used by the prosmaker CLI and by fullprosmaker during the prosody stage.",
    "metricalc": "Options used by the metricalc CLI and by fullprosmaker for metrics outputs.",
    "printer": "Options used by the printer CLI and by fullprosmaker for print outputs.",
}

OPTION_HELP = {
    "config.conf": "Path to package-wide YAML config file.",
    "logging.quiet": "Suppress informational console logging while keeping warnings and errors visible.",
    "logging.no_console": "Disable console logging entirely.",
    "logging.log": "Write runtime logs to this file.",
    "logging.log_append": "Append to --log instead of overwriting it.",
    "common.prefix": "Shared output prefix used by file-producing CLIs.",
    "common.outdir": "Shared output directory used by file-producing CLIs.",
    "common.quiet": "Suppress informational console logging while keeping warnings and errors visible.",
    "common.no_console": "Disable console logging entirely.",
    "common.log": "Optional runtime log file path.",
    "common.log_append": "Append to the configured log file instead of overwriting it.",
    "atfparser.input": "eBL ATF file (must contain %%n lines).",
    "atfparser.prefix": "Shared output prefix used by file-producing CLIs.",
    "atfparser.outdir": "Shared output directory used by file-producing CLIs.",
    "atfparser.remove_hyphens": "Remove sign-boundary hyphens in cleaned output.",
    "atfparser.preserve_case": "Preserve case from the source ATF transliteration.",
    "atfparser.preserve_h": "Preserve original h/H characters.",
    "atfparser.strict": "Enable informational warnings while parsing.",
    "atfparser.test": "Run self-test suite.",
    "atfparser.append": "Append to output files instead of overwriting them; each appended block starts on a new line.",
    "syllabifier.input": "Input file.",
    "syllabifier.prefix": "Shared output prefix used by file-producing CLIs.",
    "syllabifier.outdir": "Shared output directory used by file-producing CLIs.",
    "syllabifier.extra_vowels": "Additional characters to treat as vowels.",
    "syllabifier.extra_consonants": "Additional characters to treat as consonants.",
    "syllabifier.short_punct_chars": "Additional short-pause punctuation characters.",
    "syllabifier.long_punct_chars": "Additional long-pause punctuation characters.",
    "syllabifier.short_punct_pattern": "Repeatable regexes for short-pause punctuation segments.",
    "syllabifier.long_punct_pattern": "Repeatable regexes for long-pause punctuation segments.",
    "syllabifier.number_format": "Regex used to recognize numbers; empty uses the built-in English-grouping-compatible pattern.",
    "syllabifier.merge_hyphen": "Merge hyphens into syllable separators.",
    "syllabifier.merge_lines": "Merge lines instead of preserving source line structure.",
    "syllabifier.title": "Override inherited or missing file title in output front matter.",
    "syllabifier.test": "Run internal tests.",
    "prosmaker.input": "Input *_syl.txt file.",
    "prosmaker.prefix": "Output prefix (creates <prefix>_tilde.txt).",
    "prosmaker.outdir": "Shared output directory used by file-producing CLIs.",
    "prosmaker.style": "Accent style for prosody realization.",
    "prosmaker.mora_mode": "Mora-mode gate for accentuation attempts.",
    "prosmaker.relax_last": "For explicit + links, allow prosody realization propagation before the last linked word.",
    "prosmaker.test": "Run standard tests.",
    "prosmaker.test_diphthongs": "Run diphthong restoration tests.",
    "metricalc.input": "Input *_tilde.txt file.",
    "metricalc.input_list": "File containing a list of input files, one per line.",
    "metricalc.prefix": "Shared output prefix used by file-producing CLIs.",
    "metricalc.outdir": "Shared output directory used by file-producing CLIs.",
    "metricalc.csv": "Emit deprecated CSV output.",
    "metricalc.table": "Write human-readable metrics table output.",
    "metricalc.json": "Write JSON metrics output.",
    "metricalc.wpm": "Words per minute for speech-rate estimation.",
    "metricalc.pause_ratio": "Pause ratio as a percent of total time.",
    "metricalc.long_punct_weight": "Long-pause punctuation weight relative to short-pause punctuation.",
    "metricalc.extra_consonants": "Additional characters to treat as consonants.",
    "metricalc.extra_vowels": "Additional characters to treat as vowels.",
    "metricalc.short_punct_chars": "Additional short-pause punctuation characters.",
    "metricalc.long_punct_chars": "Additional long-pause punctuation characters.",
    "metricalc.short_punct_pattern": "Repeatable regexes for short-pause punctuation segments.",
    "metricalc.long_punct_pattern": "Repeatable regexes for long-pause punctuation segments.",
    "metricalc.explicit_link_count": "Override inherited metadata.data.prosody.explicit_word_link_count.",
    "metricalc.test": "Run unit tests.",
    "printer.input": "Input *_tilde.txt file.",
    "printer.prefix": "Shared output prefix used by file-producing CLIs.",
    "printer.outdir": "Shared output directory used by file-producing CLIs.",
    "printer.acute": "Write <prefix>_accent_acute.txt.",
    "printer.bold": "Write <prefix>_accent_bold.md.",
    "printer.ipa": "Write <prefix>_accent_ipa.txt (vowel coloring applies post-emphatic only).",
    "printer.ipa_proto_semitic": "IPA proto-Semitic policy: preserve=Old Akkadian, replace=Old Babylonian merger.",
    "printer.circ_hiatus": "Speculative IPA mode: split circumflex vowels into hiatus (for example qû -> qʊ.ʊ).",
    "printer.xar": "Write both <prefix>_accent_xar.txt and <prefix>_xar.txt.",
    "printer.mbrola": "Write <prefix>_accent_mbrola.txt (MBROLA/X-SAMPA-like symbols).",
    "printer.print_merger": "Render the visible merge connector in supported outputs.",
    "printer.test": "Run internal tests.",
    "fullprosmaker.input": "Input Akkadian file (typically *_proc.txt).",
    "fullprosmaker.prefix": "Shared output prefix for all generated files.",
    "fullprosmaker.outdir": "Shared output directory used by file-producing CLIs.",
    "fullprosmaker.extra_vowels": "Additional characters to treat as vowels.",
    "fullprosmaker.extra_consonants": "Additional characters to treat as consonants.",
    "fullprosmaker.short_punct_chars": "Additional short-pause punctuation characters.",
    "fullprosmaker.long_punct_chars": "Additional long-pause punctuation characters.",
    "fullprosmaker.short_punct_pattern": "Repeatable regexes for short-pause punctuation segments.",
    "fullprosmaker.long_punct_pattern": "Repeatable regexes for long-pause punctuation segments.",
    "fullprosmaker.number_format": "Regex used to recognize numbers in the syllabifier stage; empty uses the built-in English-grouping-compatible pattern.",
    "fullprosmaker.syl_merge_hyphens": "Merge hyphens into syllable separators in the syllabifier stage.",
    "fullprosmaker.syl_merge_lines": "Merge lines instead of preserving source line structure.",
    "fullprosmaker.title": "Override inherited or missing file title in syllabifier output front matter.",
    "fullprosmaker.prosody_style": "Accent style for the prosody stage.",
    "fullprosmaker.mora_mode": "Mora-mode gate for prosody realization attempts.",
    "fullprosmaker.prosody_relax_last": "For explicit + links, allow prosody realization propagation before the last linked word.",
    "fullprosmaker.metrics_csv": "Emit deprecated CSV metrics output.",
    "fullprosmaker.metrics_table": "Write human-readable metrics table output.",
    "fullprosmaker.metrics_json": "Write JSON metrics output.",
    "fullprosmaker.metrics_wpm": "Words per minute for speech-rate estimation.",
    "fullprosmaker.metrics_pause_ratio": "Pause ratio as a percent of total time.",
    "fullprosmaker.metrics_long_punct_weight": "Long-pause punctuation weight relative to short-pause punctuation.",
    "fullprosmaker.explicit_link_count": "Override inherited metadata.data.prosody.explicit_word_link_count for metrics.",
    "fullprosmaker.print_acute": "Write <prefix>_accent_acute.txt.",
    "fullprosmaker.print_bold": "Write <prefix>_accent_bold.md.",
    "fullprosmaker.print_ipa": "Write <prefix>_accent_ipa.txt.",
    "fullprosmaker.print_ipa_proto_semitic": "IPA proto-Semitic policy: preserve=Old Akkadian, replace=Old Babylonian merger.",
    "fullprosmaker.print_circ_hiatus": "Speculative IPA mode: split circumflex vowels into hiatus (for example qû -> qʊ.ʊ).",
    "fullprosmaker.print_xar": "Write both <prefix>_accent_xar.txt and <prefix>_xar.txt.",
    "fullprosmaker.print_merger": "Render the visible merge connector in supported outputs.",
    "fullprosmaker.test_syllabify": "Run syllabify library tests.",
    "fullprosmaker.test_prosody": "Run prosody realization library tests.",
    "fullprosmaker.test_diphthongs": "Run diphthong restoration tests.",
    "fullprosmaker.test_metrics": "Run metrics library tests.",
    "fullprosmaker.test_print": "Run print library tests.",
    "fullprosmaker.test_cli": "Run fullprosmaker CLI option-resolution tests.",
    "fullprosmaker.test_all": "Run tests for syllabify, prosody realization, diphthongs, metrics, and print.",
    "confwriter.stdout": "Print the resulting config file to stdout after writing it.",
    "confwriter.test": "Reserved for future self-tests.",
}


def help_for(key: str) -> str:
    return OPTION_HELP[key]


def config_help(section: str, key: str) -> str:
    return help_for(f"{section}.{key}")


def section_help(section: str) -> str:
    return CONFIG_SECTION_HELP[section]