from __future__ import annotations

CONFIG_FILE_COMMENTS = [
    "Package-wide Akkadian Prosody Toolkit configuration.",
    "This file uses the repository's restricted YAML subset: nested mappings, scalars, and JSON-style lists.",
    "Common keys apply across file-producing CLIs.",
    "fullprosmaker reads common plus the syllabify, prosody, phonetize, metrics, and print sections.",
]

CONFIG_SECTION_HELP = {
    "common": "Shared run options used across file-producing CLIs.",
    "atfparse": "Options specific to the atfparser CLI, grouped into process and run controls.",
    "syllabify": "Options used by the syllabifier CLI and by fullprosmaker during the syllabify stage, grouped into process and run controls.",
    "prosody": "Options used by the prosmaker CLI and by fullprosmaker during the prosody stage.",
    "phonetize": "Options used by the phonetizer CLI and by fullprosmaker during the phonetize stage.",
    "metrics": "Options used by the metricalc CLI and by fullprosmaker for metrics output selection.",
    "print": "Options used by the printer CLI and by fullprosmaker for print outputs, grouped into process and run controls.",
}

OPTION_HELP = {
    "config.conf": "Path to package-wide YAML config file.",
    "logging.quiet": "Suppress informational console logging while keeping warnings and errors visible.",
    "logging.no_console": "Disable console logging entirely.",
    "logging.log": "Write runtime logs to this file.",
    "logging.log_append": "Append to --log instead of overwriting it.",
    "common.run.prefix": "Shared output prefix used by file-producing CLIs.",
    "common.run.outdir": "Shared output directory used by file-producing CLIs.",
    "common.run.quiet": "Suppress informational console logging while keeping warnings and errors visible.",
    "common.run.no_console": "Disable console logging entirely.",
    "common.run.log": "Optional runtime log file path.",
    "common.run.log_append": "Append to the configured log file instead of overwriting it.",
    "atfparse.process.remove_hyphens": "Remove sign-boundary hyphens in cleaned output.",
    "atfparse.process.preserve_case": "Preserve case from the source ATF transliteration.",
    "atfparse.process.preserve_h": "Preserve original h/H characters.",
    "atfparse.run.strict": "Enable informational warnings while parsing.",
    "atfparse.run.append": "Append to output files instead of overwriting them; each appended block starts on a new line.",
    "syllabify.process.extra_vowels": "Additional characters to treat as vowels.",
    "syllabify.process.extra_consonants": "Additional characters to treat as consonants.",
    "syllabify.process.extra_short_punct_chars": "Additional short-pause punctuation characters.",
    "syllabify.process.extra_long_punct_chars": "Additional long-pause punctuation characters.",
    "syllabify.process.extra_short_punct_pattern": "Repeatable regexes for short-pause punctuation segments.",
    "syllabify.process.extra_long_punct_pattern": "Repeatable regexes for long-pause punctuation segments.",
    "syllabify.process.number_format": "Regex used to recognize numbers; empty uses the built-in English-grouping-compatible pattern.",
    "syllabify.process.merge_hyphen": "Merge hyphens into syllable separators.",
    "syllabify.process.merge_lines": "Merge lines instead of preserving source line structure.",
    "syllabify.run.title": "Override inherited or missing file title in output front matter.",
    "prosody.process.style": "Accent style for prosody realization.",
    "prosody.process.mora_mode": "Mora-mode gate for accentuation attempts.",
    "prosody.process.relax_last": "For explicit + links, allow prosody realization propagation before the last linked word.",
    "metrics.run.table": "Write human-readable metrics table output.",
    "metrics.run.json": "Write JSON metrics output.",
    "print.process.ipa_proto_semitic": "IPA proto-Semitic policy: preserve keeps ḥ/ḫ/ʿ/ʾ distinct; replace maps ḥ/ʿ/ʾ to ʔ while ḫ stays χ.",
    "print.run.acute": "Write <prefix>_accent_acute.txt.",
    "print.run.bold": "Write <prefix>_accent_bold.md.",
    "print.run.ipa": "Write <prefix>_accent_ipa.txt using phonetizer-owned vowel realizations.",
    "print.run.circ_hiatus": "Speculative IPA mode: split circumflex vowels into hiatus (for example qû -> qʊ.ʊ).",
    "print.run.xar": "Write both <prefix>_accent_xar.txt and <prefix>_xar.txt.",
    "print.run.print_merger": "Render the visible merge connector in supported outputs.",
    "common.prefix": "Shared output prefix used by file-producing CLIs.",
    "common.outdir": "Shared output directory used by file-producing CLIs.",
    "common.quiet": "Suppress informational console logging while keeping warnings and errors visible.",
    "common.no_console": "Disable console logging entirely.",
    "common.log": "Optional runtime log file path.",
    "common.log_append": "Append to the configured log file instead of overwriting it.",
    "atfparser.input": "eBL ATF file (must contain %%n lines).",
    "atfparser.prefix": "Shared output prefix used by file-producing CLIs.",
    "atfparser.outdir": "Shared output directory used by file-producing CLIs.",
    "atfparser.remove_hyphens": "Remove sign-boundary hyphens in cleaned output.",
    "atfparser.preserve_case": "Preserve case from the source ATF transliteration.",
    "atfparser.preserve_h": "Preserve original h/H characters.",
    "atfparser.strict": "Enable informational warnings while parsing.",
    "atfparser.test": "Run self-test suite.",
    "atfparser.append": "Append to output files instead of overwriting them; each appended block starts on a new line.",
    "atfparser.option": "Override one config path with KEY=VALUE syntax; repeatable.",
    "syllabifier.input": "Input file.",
    "syllabifier.prefix": "Shared output prefix used by file-producing CLIs.",
    "syllabifier.outdir": "Shared output directory used by file-producing CLIs.",
    "syllabifier.extra_vowels": "Additional characters to treat as vowels.",
    "syllabifier.extra_consonants": "Additional characters to treat as consonants.",
    "syllabifier.extra_short_punct_chars": "Additional short-pause punctuation characters.",
    "syllabifier.extra_long_punct_chars": "Additional long-pause punctuation characters.",
    "syllabifier.extra_short_punct_pattern": "Repeatable regexes for short-pause punctuation segments.",
    "syllabifier.extra_long_punct_pattern": "Repeatable regexes for long-pause punctuation segments.",
    "syllabifier.number_format": "Regex used to recognize numbers; empty uses the built-in English-grouping-compatible pattern.",
    "syllabifier.merge_hyphen": "Merge hyphens into syllable separators.",
    "syllabifier.merge_lines": "Merge lines instead of preserving source line structure.",
    "syllabifier.title": "Override inherited or missing file title in output front matter.",
    "syllabifier.test": "Run internal tests.",
    "syllabifier.option": "Override one config path with KEY=VALUE syntax; repeatable.",
    "prosmaker.input": "Input *_syl.txt file.",
    "prosmaker.prefix": "Output prefix (creates <prefix>_tilde.txt).",
    "prosmaker.outdir": "Shared output directory used by file-producing CLIs.",
    "prosmaker.style": "Accent style for prosody realization.",
    "prosmaker.mora_mode": "Mora-mode gate for accentuation attempts.",
    "prosmaker.relax_last": "For explicit + links, allow prosody realization propagation before the last linked word.",
    "prosmaker.test": "Run standard tests.",
    "prosmaker.test_diphthongs": "Run diphthong restoration tests.",
    "prosmaker.option": "Override one config path with KEY=VALUE syntax; repeatable.",
    "phonetizer.input": "Input *_tilde.txt file.",
    "phonetizer.prefix": "Output prefix (creates <prefix>_ophone.txt, <prefix>_phone.txt, <prefix>_ombrola.pho, and <prefix>_mbrola.pho).",
    "phonetizer.outdir": "Shared output directory used by file-producing CLIs.",
    "phonetizer.geminate_policy": "Same-consonant geminate handling policy for the phonetize stage.",
    "phonetizer.accentuation_distribution_policy": "Policy controlling how the added accentuation mora is distributed. Only applies in bi mode; mono mode skips accentuation elongation entirely.",
    "phonetizer.drift_tolerance": "Maximum local timing mismatch tolerated before strict failure.",
    "phonetizer.option": "Override one config path with KEY=VALUE syntax; repeatable. Phonetize-owned runtime paths use phonetize.process.realization.*, phonetize.process.intonation.*, and phonetize.process.timing_model.*.",
    "phonetizer.test": "Run phonetizer self-tests.",
    "metricalc.input": "Input <prefix>_phone.txt file.",
    "metricalc.input_list": "File containing a list of input files, one per line.",
    "metricalc.ophone": "Optional matching <prefix>_ophone.txt file; otherwise derived from the *_phone.txt input name.",
    "metricalc.prefix": "Shared output prefix used by file-producing CLIs.",
    "metricalc.outdir": "Shared output directory used by file-producing CLIs.",
    "metricalc.table": "Write human-readable metrics table output.",
    "metricalc.json": "Write JSON metrics output.",
    "metricalc.test": "Run unit tests.",
    "metricalc.option": "Override one config path with KEY=VALUE syntax; repeatable.",
    "printer.input": "Input <prefix>_phone.txt file.",
    "printer.ophone": "Optional matching <prefix>_ophone.txt file; otherwise derived from the *_phone.txt input name.",
    "printer.prefix": "Shared output prefix used by file-producing CLIs.",
    "printer.outdir": "Shared output directory used by file-producing CLIs.",
    "printer.acute": "Write <prefix>_accent_acute.txt.",
    "printer.bold": "Write <prefix>_accent_bold.md.",
    "printer.ipa": "Write <prefix>_accent_ipa.txt using phonetizer-owned vowel realizations.",
    "printer.ipa_proto_semitic": "IPA proto-Semitic policy: preserve keeps ḥ/ḫ/ʿ/ʾ distinct; replace maps ḥ/ʿ/ʾ to ʔ while ḫ stays χ.",
    "printer.circ_hiatus": "Speculative IPA mode: split circumflex vowels into hiatus (for example qû -> qʊ.ʊ).",
    "printer.xar": "Write both <prefix>_accent_xar.txt and <prefix>_xar.txt.",
    "printer.print_merger": "Render the visible merge connector in supported outputs.",
    "printer.test": "Run internal tests.",
    "printer.option": "Override one config path with KEY=VALUE syntax; repeatable.",
    "fullprosmaker.input": "Input Akkadian file (typically *_proc.txt).",
    "fullprosmaker.prefix": "Shared output prefix for all generated files.",
    "fullprosmaker.outdir": "Shared output directory used by file-producing CLIs.",
    "fullprosmaker.extra_vowels": "Additional characters to treat as vowels.",
    "fullprosmaker.extra_consonants": "Additional characters to treat as consonants.",
    "fullprosmaker.extra_short_punct_chars": "Additional short-pause punctuation characters.",
    "fullprosmaker.extra_long_punct_chars": "Additional long-pause punctuation characters.",
    "fullprosmaker.extra_short_punct_pattern": "Repeatable regexes for short-pause punctuation segments.",
    "fullprosmaker.extra_long_punct_pattern": "Repeatable regexes for long-pause punctuation segments.",
    "fullprosmaker.number_format": "Regex used to recognize numbers in the syllabifier stage; empty uses the built-in English-grouping-compatible pattern.",
    "fullprosmaker.syl_merge_hyphens": "Merge hyphens into syllable separators in the syllabifier stage.",
    "fullprosmaker.syl_merge_lines": "Merge lines instead of preserving source line structure.",
    "fullprosmaker.title": "Override inherited or missing file title in syllabifier output front matter.",
    "fullprosmaker.prosody_style": "Accent style for the prosody stage.",
    "fullprosmaker.mora_mode": "Mora-mode gate for prosody realization attempts.",
    "fullprosmaker.prosody_relax_last": "For explicit + links, allow prosody realization propagation before the last linked word.",
    "fullprosmaker.phonetize_geminate_policy": "Same-consonant geminate handling policy for the phonetize stage.",
    "fullprosmaker.phonetize_accentuation_distribution_policy": "Policy controlling how the added accentuation mora is distributed in the phonetize stage. Only applies in bi mode; mono mode skips accentuation elongation entirely.",
    "fullprosmaker.phonetize_drift_tolerance": "Maximum local timing mismatch tolerated before strict failure in the phonetize stage.",
    "fullprosmaker.option": "Override one config path with KEY=VALUE syntax; repeatable. Phonetize-owned runtime paths use phonetize.process.realization.*, phonetize.process.intonation.*, and phonetize.process.timing_model.*.",
    "fullprosmaker.metrics_table": "Write human-readable metrics table output.",
    "fullprosmaker.metrics_json": "Write JSON metrics output.",
    "fullprosmaker.print_acute": "Write <prefix>_accent_acute.txt.",
    "fullprosmaker.print_bold": "Write <prefix>_accent_bold.md.",
    "fullprosmaker.print_ipa": "Write <prefix>_accent_ipa.txt.",
    "fullprosmaker.print_ipa_proto_semitic": "IPA proto-Semitic policy: preserve keeps ḥ/ḫ/ʿ/ʾ distinct; replace maps ḥ/ʿ/ʾ to ʔ while ḫ stays χ.",
    "fullprosmaker.print_circ_hiatus": "Speculative IPA mode: split circumflex vowels into hiatus (for example qû -> qʊ.ʊ).",
    "fullprosmaker.print_xar": "Write both <prefix>_accent_xar.txt and <prefix>_xar.txt.",
    "fullprosmaker.print_merger": "Render the visible merge connector in supported outputs.",
    "fullprosmaker.fast": "Enable fast mode: cap input to the first 10 body lines and record fast_mode in output frontmatter.",
    "fullprosmaker.max_lines": "Process at most N non-frontmatter body lines from the proc input. Recorded as input_max_lines in output frontmatter.",
    "fullprosmaker.test_syllabify": "Run syllabify library tests.",
    "fullprosmaker.test_prosody": "Run prosody realization library tests.",
    "fullprosmaker.test_diphthongs": "Run diphthong restoration tests.",
    "fullprosmaker.test_metrics": "Run metrics library tests.",
    "fullprosmaker.test_print": "Run print library tests.",
    "fullprosmaker.test_cli": "Run fullprosmaker CLI option-resolution tests.",
    "fullprosmaker.test_all": "Run tests for syllabify, prosody realization, diphthongs, metrics, and print.",
    "confwriter.set": "Set one config key with KEY=VALUE syntax; repeatable.",
    "confwriter.get": "Print the current effective value for one config key.",
    "confwriter.list": "List schema-backed config keys, optionally filtered by substring.",
    "confwriter.unset": "Write null for one config key so it is treated as not explicitly set; repeatable.",
    "confwriter.set_default": "Write the schema default value explicitly for one config key; repeatable.",
    "confwriter.verify": "Run shared phonetize semantic verification against the effective grouped config without modifying the file.",
    "confwriter.stdout": "Print the resulting config file to stdout after writing it.",
    "confwriter.test": "Run confwriter self-tests.",

    "atfparse.remove_hyphens": "Remove sign-boundary hyphens in cleaned output.",
    "atfparse.preserve_case": "Preserve case from the source ATF transliteration.",
    "atfparse.preserve_h": "Preserve original h/H characters.",
    "atfparse.strict": "Enable informational warnings while parsing.",
    "atfparse.append": "Append to output files instead of overwriting them; each appended block starts on a new line.",
    "syllabify.extra_vowels": "Additional characters to treat as vowels.",
    "syllabify.extra_consonants": "Additional characters to treat as consonants.",
    "syllabify.extra_short_punct_chars": "Additional short-pause punctuation characters.",
    "syllabify.extra_long_punct_chars": "Additional long-pause punctuation characters.",
    "syllabify.extra_short_punct_pattern": "Repeatable regexes for short-pause punctuation segments.",
    "syllabify.extra_long_punct_pattern": "Repeatable regexes for long-pause punctuation segments.",
    "syllabify.number_format": "Regex used to recognize numbers; empty uses the built-in English-grouping-compatible pattern.",
    "syllabify.merge_hyphen": "Merge hyphens into syllable separators.",
    "syllabify.merge_lines": "Merge lines instead of preserving source line structure.",
    "syllabify.title": "Override inherited or missing file title in output front matter.",
    "prosody.style": "Accent style for prosody realization.",
    "prosody.mora_mode": "Mora-mode gate for accentuation attempts.",
    "prosody.relax_last": "For explicit + links, allow prosody realization propagation before the last linked word.",
    "metrics.table": "Write human-readable metrics table output.",
    "metrics.json": "Write JSON metrics output.",
    "print.acute": "Write <prefix>_accent_acute.txt.",
    "print.bold": "Write <prefix>_accent_bold.md.",
    "print.ipa": "Write <prefix>_accent_ipa.txt using phonetizer-owned vowel realizations.",
    "print.ipa_proto_semitic": "IPA proto-Semitic policy: preserve keeps ḥ/ḫ/ʿ/ʾ distinct; replace maps ḥ/ʿ/ʾ to ʔ while ḫ stays χ.",
    "print.circ_hiatus": "Speculative IPA mode: split circumflex vowels into hiatus (for example qû -> qʊ.ʊ).",
    "print.xar": "Write both <prefix>_accent_xar.txt and <prefix>_xar.txt.",
    "print.print_merger": "Render the visible merge connector in supported outputs.",
}


def help_for(key: str) -> str:
    return OPTION_HELP[key]


def config_help(section: str, key: str | None = None) -> str:
    if key is None:
        return help_for(section)
    return help_for(f"{section}.{key}")


def section_help(section: str) -> str:
    return CONFIG_SECTION_HELP[section]