from pathlib import Path

from akkapros._gencode.lib_diphthongs import _pivot_replacement, generate_diphthongs_file


def test_diphthong_generator_writes_autogenerated_header(tmp_path: Path) -> None:
    output = tmp_path / "diphthongs.py"
    written = generate_diphthongs_file(output)

    assert written == output
    text = output.read_text(encoding="utf-8")
    assert "autogenerated by src/akkapros/_gencode/lib_diphthongs.py" in text
    assert "ALL_REPLACEMENTS = [" in text


def test_pivot_replacement_preserves_real_syllable_boundary_for_hiatus() -> None:
    assert _pivot_replacement("ua") == "u·¨a"
    assert _pivot_replacement("uā") == "u·¨ā"
    assert _pivot_replacement("uā~") == "u·¨ā~"


def test_pivot_replacement_leaves_monophthongs_unchanged() -> None:
    assert _pivot_replacement("â") == "â"
    assert _pivot_replacement("â~") == "â~"


def test_diphthong_generator_writes_pivot_preserving_replacements(tmp_path: Path) -> None:
    output = tmp_path / "diphthongs.py"
    generate_diphthongs_file(output)

    text = output.read_text(encoding="utf-8")
    assert "(r'u·¨a', 'u·¨a')" in text
    assert "(r'(?:u·¨ā|ū·¨a)', 'u·¨ā')" in text
    assert "(r'ū·¨ā', 'u·¨ā~')" in text
    assert "(r'(?:a·¨a|â·¨â|â·¨ā|ā·¨â)', 'â')" in text
