from pathlib import Path

from akkapros._gencode.lib_diphthongs import generate_diphthongs_file


def test_diphthong_generator_writes_autogenerated_header(tmp_path: Path) -> None:
    output = tmp_path / "diphthongs.py"
    written = generate_diphthongs_file(output)

    assert written == output
    text = output.read_text(encoding="utf-8")
    assert "autogenerated by src/akkapros/_gencode/lib_diphthongs.py" in text
    assert "ALL_REPLACEMENTS = [" in text
